name: RealmAddon
main: com.extracraft.realmaddon.RealmAddonPlugin
version: 1.0.0
api-version: '1.21'
author: ExtraCraft
softdepend:
  - RealmCore
  - Iris
  - PlaceholderAPI
commands:
  realmaddon:
    description: RealmAddon admin commands
    usage: /realmaddon
permissions:
  realmaddon.use:
    default: true
  realmaddon.admin:
    default: op
